export const mainColor = '#875ef0'
export const primaryColor = '#735FEC'
export const defaultFontColor = '#150094'
export const defaultBorder = '#C4BAFF'
export const defaultInputBG = '#FCFCFC'
export const defaultInputFC = '#828282'
