export const mainColor = '#5312DF'
export const primaryColor = '#735FEC'
export const defaultFontColor = '#150094'
export const defaultBorder = '#C4BAFF'
export const defaultInputBG = '#ECECEC'
export const defaultInputFC = '#828282'
